Repository NHSISL/ISL.ReIdentification, pull requests merged in 2024-12, with the labels that each got.

#282 FOUNDATIONS: Document RetrieveAllAccessPoliciesFromContainer
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.RetrieveAllAccessPoliciesFromContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.RetrieveAllAccessPoliciesFromContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.RetrieveAllAccessPoliciesFromContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#283 FOUNDATIONS: Document RemoveAllAccessPoliciesFromContainer
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.RemoveAllAccessPoliciesFromContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.RemoveAllAccessPoliciesFromContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.RemoveAllAccessPoliciesFromContainer.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#286 CODE RUB: Playwright baseline
  .eslintignore
  .github/workflows/e2e.yml
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/dependencies/guid-typescript/package-lock.json
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/package-lock.json
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/package.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/.env
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/dependencies/guid-typescript/package-lock.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/dependencies/guid-typescript/package.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/package-lock.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/package.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/playwright.config.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/tests/auth.setup.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/tests/help.txt
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/tests/navigation.spec.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/tsconfig.app.json
  azure-pipelines.yml
Labels: CODE RUB

#290 FOUNDATIONS: Document AddContainer
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.AddContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.AddContainer.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.AddContainer.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#285 CODE RUB: Bugs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/accessAudits/accessAuditRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/accessAudits/accessAuditTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/csvIdentificationRequest/csvIdentificationRequestRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/csvIdentificationRequest/csvIdentificationRequestTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/odsData/odsTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessEdit.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessNew.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/models/csvIdentificationRequest/csvIdentificationRequest.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/models/views/components/csvIdentificationRequest/csvIdentificationRequestView.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/pages/csvIdentificationRequest.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/pages/csvIdentificationRequestDetail.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/csvIdentificationRequest/csvIdentificationRequestViewService.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/CsvIdentificationRequests/CsvIdentificationRequestsrollerTests.Security.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/CsvIdentificationRequestController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditRow.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditRowView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvIdentificationWorklist/csvIdentificationWorklistTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsHome.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/accessAudit/accessAuditViewService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/AccessAuditsController.cs
Labels: CODE RUB

#297 FOUNDATIONS: Document AddFolder
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.AddFolder.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.AddFolder.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.AddFolder.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#298 FOUNDATIONS: User Agreement
  ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Exceptions.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Exceptions.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Exceptions.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Exceptions.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Exceptions.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Logic.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Logic.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Logic.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Logic.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Logic.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Validations.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Validations.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Validations.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.Validations.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Exceptions.PersistImpersonationContext.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Exceptions.PurgeCsvReIdentificationRecordsThatExpired.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.AddUserAccess.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.BulkAddRemoveUserAccess.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.ModifyUserAccess.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RemoveUserAccessById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RetrieveAllActiveOrganisationsUserHasAccessTo.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RetrieveAllUserAccesses.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RetrieveUserAccessById.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/AlreadyExistsUserAgreementException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/FailedUserAgreementServiceException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/FailedUserAgreementStorageException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/InvalidUserAgreementException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/InvalidUserAgreementReferenceException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/LockedUserAgreementException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/NotFoundUserAgreementException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/NullUserAgreementException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/UserAgreementDependencyException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/UserAgreementDependencyValidationException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/UserAgreementServiceException.cs
  ISL.ReIdentification.Core/Models/Foundations/UserAgreements/Exceptions/UserAgreementValidationException.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAgreements/IUserAgreementService.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAgreements/UserAgreementService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAgreements/UserAgreementService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAgreements/UserAgreementService.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/package-lock.json
Labels: FOUNDATIONS

#302 FOUNDATIONS: Document GetDownloadLink
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.GetDownloadLink.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.GetDownloadLink.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.GetDownloadLink.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/IBlobStorageBroker.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS, changes requested

#279 MINOR FIX: Identification audit
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
Labels: MINOR FIX

#306 FOUNDATIONS: Document CreateDirectorySasToken
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.CreateDirectorySasToken.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.CreateDirectorySasToken.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.CreateDirectorySasToken.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#309 FOUNDATIONS: Document RemoveAccessPolicyByName
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.RemoveAccessPolicyByName.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.RemoveAccessPolicyByName.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.RemoveAccessPolicyByName.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/BlobStorageBroker.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/IBlobStorageBroker.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#310 FOUNDATIONS: Document RetrieveAllAccessPolicies
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.RetrieveAllAccessPolicies.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.RetrieveAllAccessPolicies.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.RetrieveAllAccessPolicies.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/BlobStorageBroker.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/IBlobStorageBroker.cs
  ISL.ReIdentification.Core/Models/Foundations/Documents/Policy.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
Labels: FOUNDATIONS

#320 CODE RUB: Update Timer Function Di and Name
  ISL.ReIdentification.Functions/Program.cs
  ISL.ReIdentification.Functions/PurgeReidentifiedRecordsThatHaveExpiredTimerFunction.cs
Labels: CODE RUB

#321 CODE RUB: Updated script
  .github/workflows/validatepr.yml
Labels: CODE RUB

#322 CODE RUB: Updated script
  .github/workflows/validatepr.yml
Labels: CODE RUB

#324 CODE RUB: script update
  .github/workflows/validatepr.yml
Labels: CODE RUB

#325 CODE RUB: Script update
  .github/workflows/validatepr.yml
Labels: CODE RUB

#326 CODE RUB: Add missing App Settings
  ISL.ReIdentification.Functions/appsettings.Development.json
  ISL.ReIdentification.Functions/appsettings.json
Labels: CODE RUB

#328 CODE RUB: Add Condig App Settings
  ISL.ReIdentification.Functions/appsettings.json
Labels: CODE RUB

#329 CODE RUB: Fix Config
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.PurgeCsvReIdentificationRecordsThatExpired.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
  ISL.ReIdentification.Functions/Program.cs
  ISL.ReIdentification.Functions/appsettings.json
Labels: CODE RUB

#331 CODE RUB: Style Changes
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/App.css
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/bases/layouts/BreadCrumb/BreadCrumbStyle.css
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/index.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/public/OneLondon_Logo & strap_Blue.jpg
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/public/OneLondon_Logo_OneLondon_Logo_Blue white.png
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/public/OneLondon_Logo_OneLondon_Logo_Blue.jpg
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/public/OneLondon_Logo_OneLondon_Logo_Blue.png
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/public/OneLondon_Logo_OneLondon_Logo_White.png
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/bases/layouts/BreadCrumb/BreadCrumbStyle.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/footer.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/login.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css
Labels: CODE RUB

#333 CODE RUB: Remove Branding
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/App.css
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/bases/layouts/BreadCrumb/BreadCrumbStyle.css
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/index.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/login.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css
Labels: CODE RUB

#330 ORCHESTRATIONS: Identification ExpireRenewImpersonationContextTokens
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Exceptions.ExpireRenewImpersonationContextTokens.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ExpireRenewImpersonationContextTokens.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Validations.ExpireRenewImpersonationContextTokens.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Exceptions.SendGeneratedTokensNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.SendGeneratedTokensNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Validation.PurgeCsvReIdentificationRecordsThatExpired.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Validation.SendGeneratedTokensNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/IBlobStorageBroker.cs
  ISL.ReIdentification.Core/Models/Coordinations/Identifications/ProjectStorageConfiguration.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/INotificationService.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IIdentificationOrchestrationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.Validations.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/IPersistanceOrchestrationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.Validations.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
  ISL.ReIdentification.Functions/appsettings.json
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
  ISL.Reidentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.cs
Labels: ORCHESTRATIONS

#338 CODE RUB: random change
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachModal.tsx
Labels: CODE RUB, draft

#339 CODE RUB: Fix Vite
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/vite.config.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json
Labels: CODE RUB

#340 CODE RUB: Launch Settings
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json
Labels: CODE RUB

#342 CODE RUB: Update line breaks
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/ISL.ReIdentification.Configurations.Client.esproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachDetails.tsx
Labels: CODE RUB

#343 CODE RUB: Update Branding
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/core/menu.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/login.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css
Labels: CODE RUB

#344 CODE RUB: Login Screen Brand
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/loginUnauth.tsx
Labels: CODE RUB
