Repository NHSISL/ISL.ReIdentification, pull requests merged in 2024-11, with the labels that each got.

#203 ACCEPTANCE: Ods - DELETE
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
Labels: ACCEPTANCE

#204 ACCEPTANCE: Ods - GET
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
Labels: ACCEPTANCE

#212 ACCEPTANCE: UserAccesses Post BulkUserAccess
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/UserAccessesApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/UserAccessesApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.UserAccesses.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Models/UserAccesses/BulkUserAccess.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Models/UserAccesses/UserAccess.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/TestAuthHandler.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/UserAccessesApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/UserAccessesApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.UserAccesses.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/UserAccesses/UserAccess.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/TestAuthHandler.cs
Labels: ACCEPTANCE

#205 ACCEPTANCE: Ods - GET ALL
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs
Labels: ACCEPTANCE

#210 ACCEPTANCE: Ods - GetChildren
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.OdsData.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs
Labels: ACCEPTANCE

#215 FOUNDATIONS: ReIdentification - ReIdentifyAsync
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Exceptions.BulkProcessRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Exceptions.ProcessReId.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Logic.BulkProcessRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Logic.ProcessReId.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Validations.ProcessReId.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.cs
  ISL.ReIdentification.Core/Brokers/NECS/INECSBroker.cs
  ISL.ReIdentification.Core/Brokers/NECS/NECSBroker.cs
  ISL.ReIdentification.Core/Brokers/ReIdentifications/IReIdentificationBroker.cs
  ISL.ReIdentification.Core/Brokers/ReIdentifications/ReIdentificationBroker.cs
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
  ISL.ReIdentification.Core/Models/Brokers/NECS/NECSConfiguration.cs
  ISL.ReIdentification.Core/Models/Brokers/NECS/Requests/NecsPseudonymisedItem.cs
  ISL.ReIdentification.Core/Models/Brokers/NECS/Requests/NecsReidentificationRequest.cs
  ISL.ReIdentification.Core/Models/Brokers/NECS/Responses/NecsReIdentificationResponse.cs
  ISL.ReIdentification.Core/Models/Brokers/NECS/Responses/NecsReidentifiedItem.cs
  ISL.ReIdentification.Core/Services/Foundations/ReIdentifications/ReIdentificationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/ReIdentifications/ReIdentificationService.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Resources/IdentificationPairs.csv
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Logic.ProcessReId.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.Validations.ProcessReId.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/ReIdentifications/ReIdentifactionServiceTests.cs
Labels: FOUNDATIONS

#216 CODE RUB: Refactor ReIdentification controller to pass reason when processing request
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessCsvIdentificationRequestAsync.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessCsvIdentificationRequests.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IIdentificationCoordinationService.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Validations.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Exceptions.GetCsvIdentificationRequestById.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Logic.GetCsvIdentificationRequestById.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/ReIdentificationController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Exceptions.GetCsvIdentificationRequestById.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Logic.GetCsvIdentificationRequestById.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs
Labels: CODE RUB

#211 ACCEPTANCE: Ods - GetDescendants
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.OdsData.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs
Labels: ACCEPTANCE

#217 CODE RUB: Added config switch for the ReIdentificationProvider to drive NECS / Offline use
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/TestWebApplicationFactory.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/TestWebApplicationFactory.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: CODE RUB

#213 ACCEPTANCE: Ods - GetAncestors
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.OdsData.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs
Labels: ACCEPTANCE

#221 RELEASE: v0.0.0.1
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
Labels: RELEASES

#222 RELEASES: v0.0.0.1
  .github/workflows/build.yml
Labels: RELEASES

#224 CODE RUB: To use GroupName
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetail.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/lookups/lookupViewService.ts
Labels: CODE RUB

#225 ACCEPTANCE: ReIdentification Post ImpersonationContext Approved & Denied
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Exceptions.SendImpersonationApprovedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Exceptions.SendImpersonationDeniedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Exceptions.SendImpersonationPendingApprovalNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Logic.SendImpersonationApprovedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Logic.SendImpersonationDeniedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Logic.SendImpersonationPendingApprovalNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Validations.SendImpersonationApprovedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Validations.SendImpersonationDeniedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Validations.SendImpersonationPendingApprovalNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/ReIdentificationApiTests.Logic.PostImpersonationContextRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/ReIdentificationApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/Accesses/AccessRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/CsvIdentificationRequests/CsvIdentificationRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/ReIdentifications/IdentificationItem.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/ReIdentifications/IdentificationRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: ACCEPTANCE

#228 ACCEPTANCE: CsvIdentificationRequest All CRUD Operations
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/CsvIdentificationRequestApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/CsvIdentificationRequestApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.CsvIdentificationRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/CsvIdentificationRequests/CsvIdentificationRequest.cs
Labels: ACCEPTANCE

#232 ACCEPTANCE: ReIdentification - Post List
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/OdsDatasApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/PdsDataApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/ReIdentificationApiTests.Logic.PostIdentificationRequests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/ReIdentificationApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/TestAuthHandler.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: ACCEPTANCE

#235 CODE RUB: Security Matrix Ui
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/App.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupRowNew.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/core/menu.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccess.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/securityMatrix.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/securityMatrix.tsx
Labels: CODE RUB

#246 UI - Ods Lookup Component for User Profile Screen
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.userAccess.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/ods/myOdsAssigned.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsHome.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/userProfile.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/impersonationContext/impersonationContext.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/userAccess/userAccess.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/views/components/impersonationContext/ImpersonationContextView.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/views/components/userAccess/userAccessView.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/userAccessService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/userAccess/userAccessViewService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: ready for review

#245 INTEGRATIONS: ReIdentification - Post List
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.ProcessIdentificationRequestAsync.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.AccessAudit.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.OdsDatas.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.PdsDatas.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.UserAccesses.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiTestCollection.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/TestWebApplicationFactory.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/AccessAudits/AccessAudit.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/Accesses/AccessRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/CsvIdentificationRequests/CsvIdentificationRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/ImpersonationContexts/ImpersonationContext.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/OdsDatas/OdsData.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/PdsDatas/PdsData.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/ReIdentifications/IdentificationItem.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/ReIdentifications/IdentificationRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/UserAccesses/BulkUserAccess.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/UserAccesses/UserAccess.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ReleaseCandidateFactAttribute.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ReleaseCandidateTestCaseDiscoverer.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/TestAuthHandler.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/appsettings.json
  ISL.ReIdentification.sln
Labels: INTEGRATIONS

#251 INTEGRATIONS: Identification - Post CSV
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.PersistCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.PersistImpersonationContext.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertCsvIdentificationRequestToIdentificationRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertIdentificationRequestToCsvIdentificationRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ExtractFromFilepath.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.PersistCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.PersistImpersonationContext.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessCsvIdentificationRequestAsync.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.PersistCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.PersistImpersonationContext.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.ProcessCsvIdentificationRequestAsync.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.CsvIdentificationRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessIdentificationRequests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessIdentificationRequests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessIdentificationRequests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.cs
Labels: INTEGRATIONS

#247 DATA: Created migrations for the PDS temp table, load PDS data and generate hierarchy
  ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/Scripts/CreateGenerateHeirarchyProcedure.sql
  ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/Scripts/CreateLoadPdsDataProcedure.sql
  ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/Scripts/CreatePdsTempTable.sql
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
  ISL.ReIdentification.Core/Migrations/20241113140226_CreatePdsTempTable.Designer.cs
  ISL.ReIdentification.Core/Migrations/20241113140226_CreatePdsTempTable.cs
  ISL.ReIdentification.Core/Migrations/20241113140731_CreateLoadPdsDataProcedure.Designer.cs
  ISL.ReIdentification.Core/Migrations/20241113140731_CreateLoadPdsDataProcedure.cs
  ISL.ReIdentification.Core/Migrations/20241113141318_CreateGenerateHeirarchyProcedure.Designer.cs
  ISL.ReIdentification.Core/Migrations/20241113141318_CreateGenerateHeirarchyProcedure.cs
Labels: DATA

#254 CODE RUB: UI Snags (Small)
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/index.html
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupErrors.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupRowAdd.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupRowEdit.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupRowNew.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/configurations/lookups/lookupTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/root.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccess.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/models/lookups/lookup.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/models/views/components/lookups/lookupView.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/pages/home.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/lookups/lookupViewService.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.css
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reidentificationResultView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/root.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/userProfile.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/helpers/hxHelpers.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts
Labels: CODE RUB

#258 CODE RUB: Updated packages
  .github/workflows/build.yml
  ISL.ReIdentification.Clients/ISL.ReIdentification.Clients.csproj
  ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
  ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
  ISL.ReIdentification.Infrastructure/ISL.ReIdentification.Infrastructure.csproj
  ISL.ReIdentification.Infrastructure/Services/ScriptGenerationService.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
  ISL.Reidentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
Labels: CODE RUB

#262 CODE RUB: Audit on Download
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.accessAudit.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditRow.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditRowView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDownloadDetail.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/accessAudit/accessAudit.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/accessAuditService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/accessAudit/accessAuditViewService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AuditAcesses/AccessAuditsControllerTests.Exceptions.GetAll.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AuditAcesses/AccessAuditsControllerTests.Logic.GetAll.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/AccessAuditsController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
Labels: CODE RUB

#265 CODE RUB: Update Reason in CSV to be a textArea
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
Labels: CODE RUB

#266 CODE RUB: Add Config Load into Program
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
Labels: CODE RUB

#268 INFRA: adding env files and build steps to build application for test and prod environments
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/.env.development
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/.env.production
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/.env.test
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/package.json
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/authConfig.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/.env.debug
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/.env.development
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/.env.production
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/.env.test
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/package.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/authConfig.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
  azure-pipelines.yml
Labels: INFRA

#273 BROKERS: Azure Storage - Implementing methods
  ISL.ReIdentification.Core/Brokers/Storages/Blob/BlobStorageBroker.cs
  ISL.ReIdentification.Core/Brokers/Storages/Blob/IBlobStorageBroker.cs
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
  ISL.ReIdentification.Core/Providers/Storage/FakeStorageProvider.cs
  ISL.ReIdentification.Functions/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
Labels: BROKERS
