Repository NHSISL/ISL.ReIdentification, pull requests merged in 2025-03, with the labels that each got.

#467 CODE RUB: Coordinations ReIdentification ProcessImpersonationContextAsync
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.CreateAccessRequestWithCsvIdentificationRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ExtractFromFilepath.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.cs
  ISL.ReIdentification.Core/Models/Coordinations/Identifications/Exceptions/InvalidCsvIdentificationCoordinationException.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IIdentificationCoordinationService.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Validations.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
Labels: CODE RUB, ready for review

#473 INTEGRATIONS: UserAccess
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/Lookup/LookupApiTests.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/Lookup/LookupApiTests.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/Lookup/LookupApiTests.GetById.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/Lookup/LookupApiTests.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/Lookup/LookupApiTests.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/Lookup/LookupApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApi.Tests.PostBulkUserAccess.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApiTests.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApiTests.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApiTests.GetById.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApiTests.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApiTests.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/UserAccess/UserAccessApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Brokers/ApiBroker.Lookup.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Brokers/ApiBroker.UserAccess.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Models/Lookup/Lookup.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Models/UserAccess/BulkUserAccess.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Models/UserAccess/UserAccess.cs
Labels: INTEGRATIONS

#480 CODE RUB: Testing Azure Function HttpTrigger handshake validation for event subscription
  ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs
Labels: CODE RUB

#474 INTEGRATIONS: PdsData
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/PdsData/PdsDataApiTests.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/PdsData/PdsDataApiTests.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/PdsData/PdsDataApiTests.GetbyId.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/PdsData/PdsDataApiTests.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/PdsData/PdsDataApiTests.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/PdsData/PdsDataApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Brokers/ApiBroker.PdsData.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Models/PdsData/PdsData.cs
Labels: ready for review, INTEGRATIONS

#476 INTEGRATIONS: FontendConfigurations
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/FrontendConfigurations/FrontendConfigurationApiTests.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/FrontendConfigurations/FrontendConfigurationApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Brokers/ApiBroker.FrontendConfigurations.cs
Labels: INTEGRATIONS

#477 INTEGRATIONS: CsvIdentificationRequest
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/CsvIdentificationRequest/CsvIdentificationRequestApiTests.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/CsvIdentificationRequest/CsvIdentificationRequestApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Brokers/ApiBroker.CsvIdentificationRequest.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Models/CsvIdentificationRequests/CsvIdentificationRequest.cs
Labels: INTEGRATIONS

#483 CODE RUB: Add missing services to Program.cs
  ISL.ReIdentification.Functions/Program.cs
Labels: CODE RUB

#484 CODE RUB: Add ReIdentificationProviderOfflineMode to appsettings
  ISL.ReIdentification.Functions/appsettings.json
Labels: CODE RUB

#486 CODE RUB: Update validation response object
  ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs
Labels: CODE RUB

#488 CODE RUB: Fix casing in validationResponse
  ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs
Labels: CODE RUB

#489 CODE RUB: Add additonal logging to Azure Function
  ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs
Labels: CODE RUB

#490 CODE RUB: ProjectOutboxEvent Function logging for testing locally with request body
  .gitignore
  ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs
  ISL.ReIdentification.Functions/appsettings.Development.json
Labels: CODE RUB

#491 CODE RUB: Fix TypeLoadException
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/ISL.ReIdentification.Configurations.Server.Tests.Integration.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
Labels: CODE RUB

#475 INTEGRATIONS: OdsData
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.GetAncestors.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.GetById.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.GetChildren.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.GetDescendants.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Apis/OdsData/OdsDataApiTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Brokers/ApiBroker.OdsData.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/Models/OdsData/OdsData.cs
Labels: INTEGRATIONS

#492 CODE RUB: Update Feature and menu visability
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/core/menu.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/FeaturesApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: CODE RUB, fix build issues

#493 CODE RUB: Update naming
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailManage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/impersonationContext/impersonationContext.ts
Labels: CODE RUB

#495 CODE RUB: Product 5 Usability fixes
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailManage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ImpersonationContexts/ImpersonationContextsControllerTests.Security.Get.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ImpersonationContextsController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: CODE RUB, draft
