Repository NHSISL/ISL.ReIdentification, pull requests merged in 2025-04, with the labels that each got.

#503 CODE RUB: Report Url Error Handling
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectRowView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsHome.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts
Labels: CODE RUB

#504 CODE RUB: Ui Updates
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailManage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/impersonationContextService.ts
Labels: CODE RUB

#505 CODE RUB: Bugs and word changes from Testing
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectRowView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAccessSearch/userAccessSearch.tsx
Labels: CODE RUB

#507 BUGFIX: Handle empty files
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.AddDocument.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Validations.AddDocument.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.Validations.cs
Labels: ready for review

#508 CODE RUB: Update storage provider version
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
Labels: CODE RUB, ready for review
