Repository NHSISL/ISL.ReIdentification, pull requests merged in 2025-02, with the labels that each got.

#385 CODE RUB: Update Purge CreatedBy and Check
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.PurgeCsvReIdentificationRecordsThatExpired.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
Labels: CODE RUB

#386 FOUNDATIONS: UserAccess - Audit changes
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessCsvIdentificationRequestAsync.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveAllActiveOrganisationsUserHasAccessTo.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveAllActiveOrganisationsUserHasAccessTo.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.RetrieveAllActiveOrganisationsUserHasAccessTo.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Logic.BulkAddRemoveUserAccess.cs
  ISL.ReIdentification.Core/Brokers/Securities/ISecurityBroker.cs
  ISL.ReIdentification.Core/Brokers/Securities/SecurityBroker.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.cs
  ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.cs
  ISL.ReIdentification.Functions/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/UserAccessesApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/UserAccessesApiTests.Logic.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessIdentificationRequests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessIdentificationRequests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.Modify.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RemoveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveAll.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.Modify.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RemoveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveAll.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.Modify.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.RemoveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.RetrieveById.cs
Labels: FOUNDATIONS

#389 PROVIDERS: Implemented Demo Data Provider
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: PROVIDERS

#381 CODE RUB: 1 col CSV and hook refactor
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts
Labels: CODE RUB, draft

#390 CODE RUB: Terms and Conditions Update
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/odsData/odsTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/odsData/odsDataViewService.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/pdsData/pdsDataViewService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/userProfile.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/userAgreements.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v1_0.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css
Labels: CODE RUB

#392 CODE RUB: Add Leading Zero When needed
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertCsvIdentificationRequestToIdentificationRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
Labels: CODE RUB

#395 FOUNDATIONS: Access Audit Security
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.Modify.cs
  ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.cs
  ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.Validations.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/AccessAuditsApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/AccessAuditsApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/AccessAuditsApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/AccessAuditsApiTests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.Add.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.Modify.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RemoveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RetrieveAll.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RetrieveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.Add.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.Modify.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RemoveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RetrieveAll.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RetrieveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.Add.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.Modify.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.RemoveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.RetrieveById.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.Modify.cs
Labels: FOUNDATIONS

#396 CODE RUB: Update EntraIds to strings
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/userAccess/userAccessViewService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.userAgreement.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/csvIdentificationRequest/csvIdentificationRequestViewService.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/userAccess/userAccessViewService.ts
Labels: CODE RUB

#398 CODE RUB: User Agreement Text Hide
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/UserAccessesController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/userAgreements.tsx
Labels: CODE RUB

#400 CODE RUB: Change check to max 10 numbers and numberical
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachDetails.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
Labels: CODE RUB

#401 CODE RUB: Check Visible Pages
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsLaunchPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v1_0.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/errors/error.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/reidReportHome.tsx
Labels: CODE RUB, draft

#405 CODE RUB: Ods Read-only Tree and Search
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/odsData/odsSearch.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/odsData/odsTree.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/odsData/odsTreeElement.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessEdit.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessNew.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/index.css
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/foundations/odsDataAccessService.ts
Labels: CODE RUB, draft

#406 FOUNDATIONS: Access Audit - Bulk Add
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.BulkAdd.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.BulkAdd.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.BulkAdd.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs
  ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/IReidentificationStorageBroker.AccessAudit.cs
  ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.AccessAudit.cs
  ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.cs
  ISL.ReIdentification.Core/Services/Foundations/AccessAudits/IAccessAuditService.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs
Labels: FOUNDATIONS

#409 CODE RUB: Chunking on React FileUpload
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachModal.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts
Labels: CODE RUB

#411 CONTROLLERS: PostImpersonationContextApprovalAsync stub
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IIdentificationCoordinationService.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs
Labels: CONTROLLERS

#424 CODE RUB: Add CSV Upload Limit
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: CODE RUB

#425 CODE RUB: Update frontend config
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts
Labels: CODE RUB

#414 CODE RUB: Add Logging on ProcessIdentificationRequestAsync Orchestration
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
Labels: CODE RUB, ready for review

#430 CODE RUB: Update ExpireRenewImpersonationContextTokensAsync
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.RetrieveAllContainers.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.RetrieveAllContainers.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ExpireRenewImpersonationContextTokens.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/IDocumentService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/LookupsApiTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/LookupsApiTests.cs
Labels: CODE RUB, ready for review

#433 CONFIG: Package upgrades
  ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
  ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
  ISL.Reidentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
  ISL.Reidentification.Functions/ISL.ReIdentification.Functions.csproj
  ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
Labels: CONFIG

#437 CONFIG: EF Upgrade
  ISL.Reidentification.Core/ISL.ReIdentification.Core.csproj
  ISL.Reidentification.Functions/ISL.ReIdentification.Functions.csproj
Labels: CONFIG

#436 COORDINATIONS: ReIdentitifcation AddImpersonationContextApprovalAsync
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ImpersonationContextApproval.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ImpersonationContextApproval.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ImpersonationContextApproval.cs
  ISL.ReIdentification.Core/Models/Coordinations/Identifications/Exceptions/InvalidAccessIdentificationCoordinationException.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Validations.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/IPersistanceOrchestrationService.cs
Labels: ready for review, COORDINATIONS

#438 CONFIG: Efxceptions Upgrade
  ISL.Reidentification.Core/ISL.ReIdentification.Core.csproj
  ISL.Reidentification.Functions/ISL.ReIdentification.Functions.csproj
Labels: CONFIG

#440 CONTROLLERS: ReIdentification 403 Unauthorized Exception
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessImpersonationContextRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Accesses/AccessOrchestrationServiceTests.Validations.ValidateAccessForIdentificationRequests.cs
  ISL.ReIdentification.Core/Models/Coordinations/Identifications/Exceptions/UnauthorizedIdentificationCoordinationException.cs
  ISL.ReIdentification.Core/Models/Orchestrations/Accesses/Exceptions/UnauthorizedAccessOrchestrationException.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Accesses/AccessOrchestrationService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Accesses/AccessOrchestrationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Delete.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Get.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.GetAll.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Post.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Put.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Delete.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Get.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.GetAll.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Post.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Put.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Delete.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Get.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.GetAll.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Post.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Put.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Exceptions.GetCsvIdentificationRequestById.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Exceptions.PostIdentificationRequests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessIdentificationRequests.cs
Labels: CONTROLLERS

#399 FOUNDATIONS: Csv ReIds Requests User Audit Security
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Exceptions.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Exceptions.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Exceptions.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Exceptions.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Exceptions.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Logic.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Logic.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Logic.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Logic.RetrieveAll.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Logic.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Validations.Add.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Validations.Modify.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Validations.RemoveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Validations.RetrieveById.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.cs
  ISL.ReIdentification.Core/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/CsvIdentificationRequestApiTests.Logic.cs
Labels: FOUNDATIONS, changes requested

#445 ACCEPTANCE: ReIdentification ImpersonationContextApprovalAsync
  ISL.ReIdentification.Core/Models/Coordinations/Identifications/ApprovalRequest.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/ReIdentificationApiTests.Logic.ImpersonationContextApproval.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Exceptions.PostImpersonationContextApproval.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Logic.PostImpersonationContextApproval.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs
Labels: ready for review, ACCEPTANCE

#446 INTEGRATIONS: ReIdentification ImpersonationContextApprovalAsync
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.ImpersonationContextApproval.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ImpersonationContexts.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/ReIdentifications/ApprovalRequest.cs
Labels: ready for review, INTEGRATIONS

#454 CODE RUB: add custom error for 401
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDownloadDetail.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts
Labels: CODE RUB

#456 CODE RUB: Update providers
  ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
  ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
  ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
  ISL.Reidentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
Labels: CODE RUB

#458 CODE RUB: Updates to PDS Page on Management Portal
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/core/copyIcon.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/helpers/hxHelpers.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/pdsData/pdsDataViewService.ts
Labels: CODE RUB

#461 CODE RUB: Update to check Header
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts
Labels: CODE RUB

#462 CODE RUB: Fix build issues
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Lookups/LookupServiceTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Lookups/LookupsControllerTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/Lookups/LookupsControllerTests.cs
Labels: CODE RUB
