Repository NHSISL/ISL.ReIdentification, pull requests merged in 2025-01, with the labels that each got.

#345 CODE RUB: Lowercase Reference
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
Labels: CODE RUB

#346 CODE RUB: Update management branding
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/public/OneLondon_Logo & strap_Blue.jpg
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/public/OneLondon_Logo_OneLondon_Logo_Blue white.png
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/public/OneLondon_Logo_OneLondon_Logo_Blue.jpg
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/public/OneLondon_Logo_OneLondon_Logo_Blue.png
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/public/OneLondon_Logo_OneLondon_Logo_White.png
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/footer.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
Labels: CODE RUB

#348 CODE RUB: Disable download if expired
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvIdentificationWorklist/csvIdentificationWorklistRowView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDownloadDetail.tsx
Labels: CODE RUB

#349 CODE RUB: Remove function to save error logs
  ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs
Labels: CODE RUB

#336 FOUNDATIONS: Documents CreateAndAssignAccessPolicies
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.CreateAndAssignAccessPolicies.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.CreateAndAssignAccessPolicies.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.CreateAndAssignAccessPolicies.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
  ISL.ReIdentification.Core/Models/Foundations/Documents/Exceptions/InvalidPermssionDocumentException.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Exceptions.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs
Labels: FOUNDATIONS

#350 FOUNDATIONS: Notifications SendImpersonationContextTokensGeneratedNotificationAsync
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Exceptions.SendImpersonationTokensGenerated.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Logic.SendImpersonationTokenGeneratedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Validations.SendImpersonationTokensGeneratedNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Exceptions.SendGeneratedTokensNotification.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.SendGeneratedTokensNotification.cs
  ISL.ReIdentification.Core/Models/Brokers/Notifications/NotifyConfigurations.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/INotificationService.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.Validations.cs
  ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
  ISL.ReIdentification.Functions/appsettings.json
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: FOUNDATIONS

#353 MEDIUM FIX: Identification Coordinations - Add row validation before csv persistence
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.PersistCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertCsvIdentificationRequestToIdentificationRequest.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.PersistCsvIdentificationRequests.cs
  ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ConvertCsvIdentificationRequestToIdentificationRequest.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.Validations.cs
  ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
  ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.cs
Labels: MEDIUM FIX

#355 CODE RUB: Branding updates with Wording
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/ISL.ReIdentification.Configurations.Client.esproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/accessAudits/accessAuditRowView.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/accessAudits/accessAuditTable.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/pages/home.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/vite.config.ts
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/loginUnauth.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/home.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/reidReportHome.tsx
Labels: CODE RUB

#356 CODE RUB: Better Errors on CSV Upload
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/core/menu.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/FeaturesApiTests.Logic.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: CODE RUB

#357 CODE RUB: Update TOC Wording and make model wider
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/userAgreements.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v0_2.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css
Labels: CODE RUB

#354 ACCEPTANCE: ReIdentification Post ExpireRenewImpersonationContextTokens
  .github/workflows/build.yml
  ISL.ReIdentification.Infrastructure/Services/ScriptGenerationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/ReIdentificationApiTests.Logic.ExpireRenewImpersonationContextTokens.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.ReIdentification.cs
Labels: ACCEPTANCE

#367 CODE RUB: Remove Odata Paging on portal site for access Control
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/AccessAuditsController.cs
Labels: CODE RUB

#368 CONTROLLERS: Audit
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Exceptions.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Logic.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.Security.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/AccessAudits/AccessAuditsControllerTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Exceptions.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Exceptions.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Exceptions.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Exceptions.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Exceptions.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Logic.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Logic.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Logic.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Logic.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Logic.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Security.Delete.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Security.Get.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Security.GetAll.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Security.Post.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.Security.Put.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Audits/AuditsControllerTests.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/AuditsController.cs
Labels: CONTROLLERS

#366 INTEGRATIONS: ReIdentifications ExpireRenewImpersonationContextTokens
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.ExpireRenewImpersonationContextTokens.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ImpersonationContexts.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ReIdentification.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Models/ImpersonationContexts/ImpersonationContext.cs
Labels: INTEGRATIONS

#374 CODE RUB: Update Support Email
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccess.tsx
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/userAccess/userAccessTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditTable.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDownloadDetail.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportToast.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsHome.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/helpers/hxHelpers.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/accessAudit/accessAudit.ts
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/reidReportHome.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: CODE RUB

#379 CODE RUB: Change Count population
  ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
  ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditTable.tsx
Labels: CODE RUB

#380 CODE RUB: Update OrgCode Style
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachDetails.tsx
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/userProfile.tsx
Labels: CODE RUB

#383 BROKERS: Security Broker Changes To Support Manage Identity Usage
  ISL.ReIdentification.Core/Brokers/Securities/ISecurityBroker.cs
  ISL.ReIdentification.Core/Brokers/Securities/SecurityBroker.cs
  ISL.ReIdentification.Functions/Program.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/AuditsController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/CsvIdentificationRequestController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/ImpersonationContextsController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/LookupsController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/PdsDataController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/UserAccessesController.cs
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
  ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/CsvIdentificationRequestController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ImpersonationContextsController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/LookupsController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/OdsDataController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/PdsDataController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/UserAccessesController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/UserAgreementsController.cs
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
  ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json
Labels: BROKERS
